version: '3.9'

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - '9902:80'
        depends_on:
            - php-fpm
        container_name: message_channel_app_nginx_1

    php-fpm:
        build:
            context: .
            dockerfile: _docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - mariadb
            - test-mariadb
        container_name: message_channel_app_php_fpm_1

    mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - ./_docker/db:/var/lib/mysql
        ports:
            - '4400:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        container_name: message_channel_app_mariadb_1

    test-mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - ./_docker/db-test:/var/lib/mysql
        ports:
            - '4401:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_TEST_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_TEST_DATABASE}'
            MYSQL_USER: '${DB_TEST_USERNAME}'
            MYSQL_PASSWORD: '${DB_TEST_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        container_name: message_channel_app_test_mariadb_1

    redis:
        image: 'redis:alpine'
        container_name: app_redis
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - ./_docker/data/redis:/data
        ports:
            - "8002:6379"

